joint_map:
  # --- HEAD ---
  19: "neck_yaw"
  20: "neck_pitch"

  # --- LEFT ARM ---
  2: "left_shoulder_pitch"
  4: "left_shoulder_roll"
  24: "left_shoulder_yaw"
  6: "left_shoulder_elbow"
  # 22: "left_gripper"

  # --- RIGHT ARM ---
  1: "right_shoulder_pitch"
  3: "right_shoulder_roll"
  23: "right_shoulder_yaw"
  5: "right_elbow"
  # 21: "right_gripper"

  # --- LEFT LEG --- 
  8: "left_hip_yaw"
  10: "left_hip_roll"
  12: "left_hip_pitch"
  14: "left_knee"
  16: "left_ankle_pitch"
  18: "left_ankle_roll"

  # --- RIGHT LEG ---
  7: "right_hip_yaw"
  9: "right_hip_roll"
  11: "right_hip_pitch"
  13: "right_knee"
  15: "right_ankle_pitch"
  17: "right_ankle_roll"

